// Data: 20 categories with projects (short descriptions)
const data = {
  "DC Motor": [
    {
      title: "Basic DC Motor",
      description:
        "Learn how to build a simple DC motor using magnets, wire, and a battery.",
    },
    {
      title: "Brushless DC Motor",
      description:
        "Introduction to building a brushless DC motor for more efficiency.",
    },
  ],
  Drone: [
    {
      title: "Quadcopter Frame",
      description:
        "Build a strong and lightweight quadcopter frame using aluminum rods.",
    },
    {
      title: "Flight Controller Setup",
      description:
        "Step-by-step guide to install and configure your drone’s flight controller.",
    },
  ],
  "Solar Power": [
    {
      title: "Solar Charger",
      description: "Make a portable solar charger for your small devices.",
    },
    {
      title: "Solar Water Heater",
      description:
        "DIY solar water heater to reduce energy costs at home.",
    },
  ],
  Robotics: [
    {
      title: "Line Following Robot",
      description:
        "Build a robot that follows a line using infrared sensors.",
    },
    {
      title: "Obstacle Avoidance Robot",
      description:
        "Create a robot that detects and avoids obstacles in its path.",
    },
  ],
  "3D Printer": [
    {
      title: "3D Printer Basics",
      description:
        "Introduction to building a DIY 3D printer from scratch.",
    },
    {
      title: "Calibrating Your 3D Printer",
      description:
        "Learn how to calibrate and maintain your 3D printer for best results.",
    },
  ],
  "Electric Vehicle": [
    {
      title: "DIY Electric Bicycle",
      description:
        "Convert a regular bike into an electric bike using a motor kit.",
    },
    {
      title: "Battery Management System",
      description:
        "Basics of creating a battery management system for EVs.",
    },
  ],
  "Home Automation": [
    {
      title: "Smart Lights",
      description:
        "Control your home lights using Arduino and a smartphone app.",
    },
    {
      title: "Automated Door Lock",
      description:
        "Build a secure door lock that you can control remotely.",
    },
  ],
  "Water Purification": [
    {
      title: "Solar Water Purifier",
      description:
        "DIY solar-powered water purifier using simple materials.",
    },
    {
      title: "Charcoal Filter",
      description:
        "Make a charcoal water filter to clean drinking water.",
    },
  ],
  "Wind Energy": [
    {
      title: "Mini Wind Turbine",
      description:
        "Build a small wind turbine to generate electricity at home.",
    },
    {
      title: "Wind Energy Storage",
      description:
        "How to store energy generated by wind turbines efficiently.",
    },
  ],
  "3D Scanner": [
    {
      title: "DIY 3D Scanner",
      description:
        "Build your own 3D scanner with a camera and rotating platform.",
    },
    {
      title: "3D Scanning Software",
      description:
        "Open source software recommendations for 3D scanning projects.",
    },
  ],
  "Wearable Tech": [
    {
      title: "Fitness Tracker",
      description:
        "Create a simple fitness tracker with step counting features.",
    },
    {
      title: "Smartwatch Basics",
      description:
        "Introduction to building a smartwatch from open source hardware.",
    },
  ],
  "Artificial Intelligence": [
    {
      title: "AI Chatbot",
      description:
        "Build a simple AI chatbot using JavaScript.",
    },
    {
      title: "Image Recognition",
      description:
        "Implement a basic image recognition app for fun projects.",
    },
  ],
  "3D Modeling": [
    {
      title: "Blender Basics",
      description:
        "Learn to create 3D models using Blender software.",
    },
    {
      title: "Exporting Models",
      description:
        "How to export 3D models for printing or game engines.",
    },
  ],
  "Renewable Energy": [
    {
      title: "Hybrid Power Systems",
      description:
        "Combine solar and wind power for efficient renewable energy.",
    },
    {
      title: "Energy Storage Solutions",
      description:
        "Explore battery types for renewable energy storage.",
    },
  ],
  "IoT Projects": [
    {
      title: "Smart Plant Monitor",
      description:
        "Track soil moisture and light for your plants remotely.",
    },
    {
      title: "IoT Weather Station",
      description:
        "Build a station that reports temperature and humidity online.",
    },
  ],
  "3D Animation": [
    {
      title: "Animating Basics",
      description:
        "Learn the fundamentals of 3D animation for beginners.",
    },
    {
      title: "Using Keyframes",
      description:
        "Create smooth animations by using keyframe techniques.",
    },
  ],
  "Electric Circuits": [
    {
      title: "Simple Circuit Board",
      description:
        "Design and solder a basic circuit board for LED control.",
    },
    {
      title: "Transistor Switch",
      description:
        "Understand and build a transistor switch for electronics projects.",
    },
  ],
  "Gaming Consoles": [
    {
      title: "Retro Gaming Console",
      description:
        "Build a mini retro gaming console using Raspberry Pi.",
    },
    {
      title: "Game Controller",
      description:
        "Make a custom game controller for your PC or console.",
    },
  ],
  "Drones": [
    {
      title: "FPV Racing Drone",
      description:
        "Assemble a first-person-view racing drone for speed.",
    },
    {
      title: "Drone Camera Mount",
      description:
        "Create a stable camera mount for aerial photography.",
    },
  ],
  "Mechanical Inventions": [
    {
      title: "Hydraulic Arm",
      description:
        "Build a simple robotic arm using hydraulics and syringes.",
    },
    {
      title: "Gearbox Design",
      description:
        "Understand and build a basic mechanical gearbox.",
    },
  ],
};

const categories = Object.keys(data);

// Elements
const categoriesContainer = document.getElementById("categories");
const projectsSection = document.getElementById("projects");
const projectList = document.getElementById("project-list");
const categoryTitle = document.getElementById("category-title");
const backBtn = document.getElementById("back-btn");

// Initialize: Show categories on load
function showCategories() {
  projectsSection.classList.add("hidden");
  categoriesContainer.innerHTML = "";
  categoriesContainer.classList.remove("hidden");

  categories.forEach((cat) => {
    const card = document.createElement("div");
    card.className = "category-card";
    card.textContent = cat;
    card.onclick = () => showProjects(cat);
    categoriesContainer.appendChild(card);
  });
}

// Show projects of a category
function showProjects(category) {
  categoryTitle.textContent = category;
  projectList.innerHTML = "";
  categoriesContainer.classList.add("hidden");
  projectsSection.classList.remove("hidden");

  const projects = data[category] || [];

  projects.forEach((proj) => {
    const div = document.createElement("div");
    div.className = "project-item";
    div.innerHTML = `<strong>${proj.title}</strong><br/>${proj.description}`;
    projectList.appendChild(div);
  });
}

// Back button to categories
backBtn.onclick = () => {
  showCategories();
};

// Initial call
showCategories();