// videos.js
// Preloaded videos data (will show before Firebase videos load)
const preloadedVideos = [
  {
    id: "pre1",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=QGJuMBdaqIw",
    thumbnailUrl: "https://img.youtube.com/vi/QGJuMBdaqIw/hqdefault.jpg",
    title: "Cocomelon - Bath Song",
    category: "Kids",
    description: "Fun bath time song for kids",
    likesCount: 0,
  },
  {
    id: "pre2",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=3n4K7MfOQOA",
    thumbnailUrl: "https://img.youtube.com/vi/3n4K7MfOQOA/hqdefault.jpg",
    title: "Baby Shark Dance",
    category: "Kids",
    description: "Baby Shark song video",
    likesCount: 0,
  },
  {
    id: "pre3",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=Zi_XLOBDo_Y",
    thumbnailUrl: "https://img.youtube.com/vi/Zi_XLOBDo_Y/hqdefault.jpg",
    title: "Shape of You - Ed Sheeran",
    category: "Songs",
    description: "Popular song by Ed Sheeran",
    likesCount: 0,
  },
  {
    id: "pre4",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=kXYiU_JCYtU",
    thumbnailUrl: "https://img.youtube.com/vi/kXYiU_JCYtU/hqdefault.jpg",
    title: "Numb - Linkin Park",
    category: "Songs",
    description: "Popular rock song",
    likesCount: 0,
  },
  {
    id: "pre5",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=5MgBikgcWnY",
    thumbnailUrl: "https://img.youtube.com/vi/5MgBikgcWnY/hqdefault.jpg",
    title: "Learn Algebra Basics",
    category: "Learning",
    description: "Intro to Algebra",
    likesCount: 0,
  },
  {
    id: "pre6",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=rfscVS0vtbw",
    thumbnailUrl: "https://img.youtube.com/vi/rfscVS0vtbw/hqdefault.jpg",
    title: "Python Tutorial for Beginners",
    category: "Learning",
    description: "Python full course",
    likesCount: 0,
  },
  {
    id: "pre7",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=1Zf44DxJ9yo",
    thumbnailUrl: "https://img.youtube.com/vi/1Zf44DxJ9yo/hqdefault.jpg",
    title: "Cocomelon - Wheels on the Bus",
    category: "Kids",
    description: "Classic kids song",
    likesCount: 0,
  },
  {
    id: "pre8",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=2Vv-BfVoq4g",
    thumbnailUrl: "https://img.youtube.com/vi/2Vv-BfVoq4g/hqdefault.jpg",
    title: "Perfect - Ed Sheeran",
    category: "Songs",
    description: "Romantic song",
    likesCount: 0,
  },
  {
    id: "pre9",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=VYOjWnS4cMY",
    thumbnailUrl: "https://img.youtube.com/vi/VYOjWnS4cMY/hqdefault.jpg",
    title: "Old Town Road",
    category: "Songs",
    description: "Popular country rap song",
    likesCount: 0,
  },
  {
    id: "pre10",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=H14bBuluwB8",
    thumbnailUrl: "https://img.youtube.com/vi/H14bBuluwB8/hqdefault.jpg",
    title: "JavaScript Tutorial",
    category: "Learning",
    description: "Learn JavaScript basics",
    likesCount: 0,
  },
  {
    id: "pre11",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    thumbnailUrl: "https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg",
    title: "Gangnam Style",
    category: "Songs",
    description: "Popular K-pop video",
    likesCount: 0,
  },
  {
    id: "pre12",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=SbUBMklQSVU",
    thumbnailUrl: "https://img.youtube.com/vi/SbUBMklQSVU/hqdefault.jpg",
    title: "Cocomelon - ABC Song",
    category: "Kids",
    description: "Learn ABCs with song",
    likesCount: 0,
  },
  {
    id: "pre13",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=fRh_vgS2dFE",
    thumbnailUrl: "https://img.youtube.com/vi/fRh_vgS2dFE/hqdefault.jpg",
    title: "Sorry - Justin Bieber",
    category: "Songs",
    description: "Popular pop song",
    likesCount: 0,
  },
  {
    id: "pre14",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=ZbZSe6N_BXs",
    thumbnailUrl: "https://img.youtube.com/vi/ZbZSe6N_BXs/hqdefault.jpg",
    title: "Happy - Pharrell Williams",
    category: "Songs",
    description: "Feel-good song",
    likesCount: 0,
  },
  {
    id: "pre15",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=ysz5S6PUM-U",
    thumbnailUrl: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    title: "Learn Colors",
    category: "Kids",
    description: "Colors for children",
    likesCount: 0,
  },
  {
    id: "pre16",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=QQU9slIP7p8",
    thumbnailUrl: "https://img.youtube.com/vi/QQU9slIP7p8/hqdefault.jpg",
    title: "English Grammar Basics",
    category: "Learning",
    description: "Grammar lessons",
    likesCount: 0,
  },
  {
    id: "pre17",
    username: "DhogoAdmin",
    videoUrl: "https://www.youtube.com/watch?v=OHhUIb3Ub9c",
    thumbnailUrl: "https://img.youtube.com/vi/OHhUIb3Ub9c/hqdefault.jpg